name: Projeto MusicLibraryPagarMe CI-ECR

on:
  push:
    branches: 
      - dev

  pull_request:
    branches: 
      - main


defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: develop
    permissions:
      packages: write
      contents: read 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configura AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create ECR_REPOSITORY
      run: |
        aws ecr describe-repositories --repository-names ${{ secrets.REPO_NAME }} \
                                      --region ${{ secrets.AWS_REGION }} 2>&1 > /dev/null || aws ecr create-repository \
                --repository-name ${{ secrets.REPO_NAME }} \
                --region ${{ secrets.AWS_REGION }} \
                --tags '[{"Key":"env","Value":"dev"},{"Key":"team","Value":"devops"}]'
    - name: Login na Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        IMAGE_TAG: 'v1'
      run: |
        cd app/
        # Faz o build da image docker container e push para ECR 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image para ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Terraform credentials
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: |
        cd terraform
        terraform init
    - name: Terraform Plan
      id: plan
      run: |
        cd terraform
        terraform plan -no-color -var="ecs_image_url=${{ steps.build-image.outputs.image }}" -lock=false
    
    #- name: Terraform Apply
    #  id: apply
    #  run: |
    #    cd terraform
    #    terraform apply --auto-approve -no-color -var="ecs_image_url=${{ steps.build-image.outputs.image }}"

    - name: Terraform Destroy
      id: destroy
      run: |
        cd terraform
        terraform destroy --auto-approve -no-color -var="ecs_image_url=${{ steps.build-image.outputs.image }}" -lock=false
